import { defineThemeSpec } from "@omerdlw/base-framework/theme";

type PrimitivesThemeSlot =
  | "adaptiveImage"
  | "adaptiveImageFallback"
  | "adaptiveImageFrame"
  | "avatar"
  | "avatarFallback"
  | "avatarImage"
  | "backdropHero"
  | "backdropHeroGradient"
  | "backdropHeroImage"
  | "badge"
  | "button"
  | "checkbox"
  | "checkboxIndicator"
  | "fieldBar"
  | "fieldFloat"
  | "fieldInline"
  | "fieldStack"
  | "fullscreen"
  | "fullscreenContent"
  | "input"
  | "loader"
  | "loaderInline"
  | "progress"
  | "progressIndicator"
  | "selectCheck"
  | "selectChevron"
  | "selectContent"
  | "selectEmpty"
  | "selectIcon"
  | "selectLabel"
  | "selectOption"
  | "selectOptionBody"
  | "selectOptionContent"
  | "selectOptionDescription"
  | "selectPlaceholder"
  | "selectRoot"
  | "selectText"
  | "selectTrigger"
  | "selectTriggerContent"
  | "separator"
  | "skeleton"
  | "spinner"
  | "stack"
  | "stackBase"
  | "stackTop"
  | "switch"
  | "switchThumb"
  | "textarea"
  | "tooltip";

export const primitivesTheme =
  defineThemeSpec<PrimitivesThemeSlot>("primitives");
