import AccountLikesFeed from '@/features/account/feeds/likes';
import { AccountPageShell } from '@/features/account/profile/layout';
import Registry from './registry';

export default function LikesView({
  activeSegment,
  auth,
  canShowLikesGrid,
  currentPage,
  favoriteShowcase,
  followerCount,
  followingCount,
  followState,
  handleEditProfile,
  handleFollow,
  handleLike,
  handleOpenFollowList,
  handleRequestRemoveLike,
  handleSegmentChange,
  handleSignInRequest,
  handleToggleShowcase,
  hasMoreReviews,
  isBioSurfaceOpen,
  isFollowLoading,
  isLikedListsLoading,
  isOwner,
  isPageLoading,
  isReviewsLoading,
  isResolvingProfile,
  isShowcaseSaving,
  itemRemoveConfirmation,
  likedLists,
  likedListsError,
  likeCount,
  likes,
  listCount,
  loadReviews,
  pendingFollowRequestCount,
  persistShowcase,
  profile,
  resolveError,
  resolvedUserId,
  reviews,
  reviewsError,
  setIsBioSurfaceOpen,
  showcaseMap,
  unfollowConfirmation,
  username,
  watchedItems,
  watchlistCount,
}) {
  const pageRegistry = (
    <Registry
      activeSegment={activeSegment}
      auth={auth}
      canShowLikesGrid={canShowLikesGrid}
      followState={followState}
      handleEditProfile={handleEditProfile}
      handleFollow={handleFollow}
      handleOpenFollowList={handleOpenFollowList}
      handleSegmentChange={handleSegmentChange}
      handleSignInRequest={handleSignInRequest}
      isBioSurfaceOpen={isBioSurfaceOpen}
      isFollowLoading={isFollowLoading}
      isOwner={isOwner}
      isPageLoading={isPageLoading}
      isResolvingProfile={isResolvingProfile}
      itemRemoveConfirmation={itemRemoveConfirmation}
      pendingFollowRequestCount={pendingFollowRequestCount}
      profile={profile}
      resolveError={resolveError}
      setIsBioSurfaceOpen={setIsBioSurfaceOpen}
      unfollowConfirmation={unfollowConfirmation}
      username={username}
    />
  );

  return (
    <AccountPageShell
      activeSection="likes"
      followerCount={followerCount}
      followState={followState}
      followingCount={followingCount}
      isLoading={isPageLoading}
      isFollowLoading={isFollowLoading}
      isOwner={isOwner}
      likesCount={likeCount}
      listsCount={listCount}
      onFollow={handleFollow}
      onOpenFollowList={handleOpenFollowList}
      onReadMore={() => setIsBioSurfaceOpen(true)}
      profile={profile}
      registry={pageRegistry}
      resolvedUserId={resolvedUserId}
      skeletonVariant="collection"
      username={username}
      watchedCount={profile?.watchedCount || 0}
      watchlistCount={watchlistCount}
    >
      <AccountLikesFeed
        activeSegment={activeSegment}
        auth={auth}
        canShowLikesGrid={canShowLikesGrid}
        currentPage={currentPage}
        favoriteShowcase={favoriteShowcase}
        handleLike={handleLike}
        handleRequestRemoveLike={handleRequestRemoveLike}
        handleToggleShowcase={handleToggleShowcase}
        hasMoreReviews={hasMoreReviews}
        isLikedListsLoading={isLikedListsLoading}
        isOwner={isOwner}
        isReviewsLoading={isReviewsLoading}
        isShowcaseSaving={isShowcaseSaving}
        likedLists={likedLists}
        likedListsError={likedListsError}
        likes={likes}
        loadReviews={loadReviews}
        persistShowcase={persistShowcase}
        reviews={reviews}
        reviewsError={reviewsError}
        showcaseMap={showcaseMap}
        username={username}
        watchedItems={watchedItems}
      />
    </AccountPageShell>
  );
}
