// Auth public facade: consumers depend on this stable interface while the
// implementation remains organized by policy, adapter, flow and runtime.
export {
  AUTH_STATUS,
  DEFAULT_AUTH_ENDPOINTS,
  DEFAULT_AUTH_CONFIG,
  DEFAULT_AUTH_STATE,
  EMAIL_PROVIDER_ID,
  GITHUB_PROVIDER_ID,
  GOOGLE_PROVIDER_ID,
  OAUTH_PROVIDER_CONFIG,
  OAUTH_PROVIDER_KEYS,
  PASSKEY_PROVIDER_CONFIG,
  PASSKEY_PROVIDER_ID,
  X_PROVIDER_ID,
  buildOAuthCallbackUrl,
  canAccess,
  createAuthStorage,
  getAuthProviderConfig,
  getEnabledOAuthProviderIds,
  getOAuthProviderConfig,
  getOAuthProviderId,
  getOAuthProviderLabel,
  hasAllCapabilities,
  hasAnyCapability,
  hasAnyRole,
  hasCapability,
  hasRole,
  isSessionExpired,
  isSupportedOAuthProvider,
  mergeUserIntoSession,
  normalizeOAuthIntent,
  normalizeOAuthProvider,
  normalizeProviderId,
  normalizeSession,
  resolveAuthCapabilities,
  resolveOAuthIntent,
  resolvePrimaryProvider,
  sanitizeAuthNextPath,
  uniqueStrings,
} from './config';

export {
  AuthRequestError,
  clearCanonicalSessionPayloadCache,
  createAuthAdapter,
  createSupabaseAuthAdapter,
  fetchCanonicalSessionPayload,
  isCanonicalSessionAuthenticated,
  isPasskeyBrowserSupported,
  isPasskeyFeatureEnabled,
  requestAuthJson,
  usePasskeySupport,
} from './adapter';

export {
  runAuthInitialize,
  runAuthProviderMutation,
  runAuthReauthenticate,
  runAuthRefreshSession,
  runAuthSignIn,
  runAuthSignOut,
  runAuthSignUp,
  runAuthUpdateProfile,
} from './flows';

export {
  AnonymousGate,
  AuthGate,
  AuthProvider,
  useAuth,
  useAuthActions,
  useAuthConfig,
  useAuthorization,
  useAuthSessionReady,
  useAuthState,
} from './runtime';
